name: mobile_client
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  bloc: ^8.1.4
  build_runner: ^2.4.9
  cached_network_image: ^3.3.1
  dio: ^5.4.2+1
  equatable: ^2.0.5
  floor: ^1.4.2
  floor_generator: ^1.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.8
  intl: ^0.18.1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
